# Commands made for linux or WSL terminal

# Compiles the server executable
# make server
evoting:
	gcc evoting.c -o server


clean:
	rm -f evoting server

# Performs the whole process of cleaning and compilation of files and clears the terminal
# make whole
whole:
	make clean ; make evoting ; clear